#!/bin/bash
# Set the Internal Field Separator (IFS) to colon (:)
IFS=":"
# Read the /etc/passwd file line by line
while read -r username password uid gid info home_directory shell
do
  echo "The user $username is part of the $gid gang, lives in $home_directory and rides $shell. User ID's place is protected by the passcode $password, more info about the user here: $info"
done < /etc/passwd
