#!/usr/bin/env bash
#The following command creates the file /var/run/myscript.pid containing its PID, It Displays “To infinity and beyond” indefinitely, it also displays “I hate the kill command” when receiving a SIGTERM signal, it also displays “Y U no love me?!” when receiving a SIGINT signal, and Deletes the file /var/run/myscript.pid and terminates itself when receiving a SIGQUIT or SIGTERM signal
sudo bash -c "echo $$ > /var/run/myscript.pid"
trap 'echo "Y U no love me?!"' SIGINT
trap 'echo "I hate the kill command"; sudo rm -f /var/run/myscript.pid;exit' SIGTERM
trap 'sudo rm -f /var/run/myscript.pid; exit' SIGQUIT
while :
do
      echo "To infinity and beyond"
      sleep 2
done
