#!/usr/bin/env bash
#The following command manages the created bash script 
case "$1" in
  start)
    ./manage_my_process &
    echo $! > /var/run/my_process.pid
    echo "manage_my_process started"
    ;;
  stop)
    if [ -f /var/run/my_process.pid ]; then
      kill $(cat /var/run/my_process.pid)
      rm /var/run/my_process.pid
      echo "manage_my_process stopped"
    else
      echo "manage_my_process is not running"
    fi
    ;;
  restart)
    if [ -f /var/run/my_process.pid ]; then
      kill $(cat /var/run/my_process.pid)
      rm /var/run/my_process.pid
    fi
    ./manage_my_process &
    echo $! > /var/run/my_process.pid
    echo "manage_my_process restarted"
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    ;;
esac
