#!/usr/bin/env bash
#The following commands write a bash script that displays ”To infinity and beyond indefinitely”, with a sleep 2 in between each iteration and “I am invincible!!!” when receiving a “SIGTERM” signal
while :
do
       echo "To infinity and beyond"
       sleep 2
       trap 'echo "I am invincible!!!"' SIGTERM
done
